#!/usr/bin/env python2

from docker import Client

def s(str):
    return str[0:12]

cli = Client(base_url='unix://var/run/docker.sock')
images = cli.images(all=True)

imd = dict((i['Id'], i) for i in images)

def recurse(id, level=0):
    i = imd[id]
    tag = i['RepoTags'][0]
    if tag == '<none>:<none>':
        tag = ''
    print (level * '  '), '+--', s(id), tag
    for j in images:
        if j['ParentId'] == id:
            recurse(j['Id'], level + 1)

for i in images:
    if not i['ParentId']:
        recurse(i['Id'])
