#!/usr/bin/env python

from __future__ import print_function
import sys

try:
    from docker import Client
except ImportError:
    print("Cannot import Docker API, is package docker_py installed?", file=sys.stderr)
    sys.exit(1)

def s(str):
    return str[0:12]

cli = Client(base_url='unix://var/run/docker.sock')
images = cli.images(all=True)

imd = dict((i['Id'], i) for i in images)

def recurse(id, level=0):
    i = imd[id]
    tag = i['RepoTags'][0]
    if tag == '<none>:<none>':
        tag = ''
    print((level * '  '), '+--', s(id), tag)
    for j in images:
        if j['ParentId'] == id:
            recurse(j['Id'], level + 1)

for i in images:
    if not i['ParentId']:
        recurse(i['Id'])
